services:
  elasticsearch:
    image: elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic
  logstash:
    image: logstash:8.10.1
    container_name: logstash
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logs:/usr/share/logstash/data/logs
      - ./logstash/pipeline/logstash-cdn-logs.config:/usr/share/logstash/pipeline/logstash-cdn-logs.config
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: logstash -f /usr/share/logstash/pipeline/logstash-cdn-logs.config
  kibana:
    image: kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      INTERACTIVESETUP_ENABLED: false
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  elastic:
    driver: bridge
